# Dockerfile for installing the necessary dependencies for running Hadoop and Spark

FROM debian:latest

RUN apt-get update -y
RUN apt-get upgrade -y

#Configure nutch and root users
RUN apt-get install sudo
RUN adduser --disabled-password --gecos "" solr
RUN echo 'solr:solr' | chpasswd
RUN echo 'root:solr' | chpasswd
RUN echo 'solr ALL=NOPASSWD:ALL' >> /etc/sudoers
RUN echo 'DISPLAY=:0' >> /etc/environment
USER solr
ENV USER=solr

# install openjdk
RUN sudo apt-get install -y apt-utils openjdk-8-jdk curl 
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV PATH $PATH:$JAVA_HOME/bin

# install and configure ssh service
RUN sudo apt-get install -y openssh-server \
    && sudo mkdir -p /var/run/sshd

# Configure tzdata
ENV DEBIAN_FRONTEND=noninteractive
RUN sudo apt-get install -y tzdata libio-tee-perl
RUN echo "Europe/Bucharest" | sudo tee /etc/timezone
RUN sudo dpkg-reconfigure -f noninteractive tzdata

# set supervisor
RUN sudo apt-get install -y supervisor xvfb x11vnc tightvncserver fluxbox
RUN mkdir -p /tmp/root-vnc/
ENV RFBAUTH_PASSWORD_FILE=/tmp/root-vnc/passwd
ENV DISPLAY=:0

RUN echo "solr" | vncpasswd -f | sudo tee $RFBAUTH_PASSWORD_FILE
RUN	echo "[program:Xvfb]" | sudo tee -a /etc/supervisor/supervisord.conf \
	&& echo "command=/usr/bin/Xvfb $DISPLAY -screen 0 1920x1080x16" | sudo tee -a /etc/supervisor/supervisord.conf && \
	echo "[program:fluxbox]" | sudo tee -a /etc/supervisor/supervisord.conf \
	&& echo "command=/usr/bin/fluxbox" | sudo tee -a /etc/supervisor/supervisord.conf && \
	echo "[program:x11vnc]" | sudo tee -a /etc/supervisor/supervisord.conf \
	&& echo "command=/usr/bin/x11vnc -display $DISPLAY -bg -loop -forever -xkb -rfbauth $RFBAUTH_PASSWORD_FILE" | sudo tee -a /etc/supervisor/supervisord.conf

# install general tools
RUN sudo apt-get install -y iproute2 vim git inetutils-ping netcat libtool autoconf build-essential firefox-esr net-tools zip lsof

# Configure solr
WORKDIR /home/solr/
ADD solr-7.3.1 solr
RUN sudo chmod -R 777 solr
RUN sudo rm -r solr/server/solr/cores

# Configure zk-node
WORKDIR /home/solr
ADD zookeeper-3.5.5 zookeeper
RUN sudo chmod -R 777 zookeeper

EXPOSE 8983

RUN sudo apt-get clean
CMD [ "sudo", "/usr/bin/supervisord" , "-n" ]
