# Dockerfile for installing the necessary dependencies for running Hadoop and Spark

FROM debian:latest

RUN apt-get update -y
RUN apt-get upgrade -y

#Configure nutch and root users
RUN apt-get install sudo
RUN adduser --disabled-password --gecos "" nutch
RUN echo 'nutch:nutch' | chpasswd
RUN echo 'root:hadoop' | chpasswd
RUN echo 'nutch ALL=NOPASSWD:ALL' >> /etc/sudoers
RUN echo 'DISPLAY=:0' >> /etc/environment
USER nutch
ENV USER=nutch

# install openjdk
RUN sudo apt-get install -y apt-utils openjdk-8-jdk curl 
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV PATH $PATH:$JAVA_HOME/bin

# install and configure ssh service
RUN sudo apt-get install -y openssh-server \
    && sudo mkdir -p /var/run/sshd

# configure ssh free key access
WORKDIR /home/nutch/
RUN mkdir .ssh
RUN ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" \
    && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys \
    && echo "HashKnownHosts no" >> ~/.ssh/config \
    && echo "StrictHostKeyChecking no" >> ~/.ssh/config

# Configure tzdata
ENV DEBIAN_FRONTEND=noninteractive
RUN sudo apt-get install -y tzdata libio-tee-perl
RUN echo "Europe/Bucharest" | sudo tee /etc/timezone
RUN sudo dpkg-reconfigure -f noninteractive tzdata

# set supervisor
RUN sudo apt-get install -y supervisor xvfb x11vnc tightvncserver fluxbox
RUN mkdir -p /tmp/root-vnc/
ENV RFBAUTH_PASSWORD_FILE=/tmp/root-vnc/passwd
ENV DISPLAY=:0

RUN echo "hadoop" | vncpasswd -f | sudo tee $RFBAUTH_PASSWORD_FILE
RUN echo "[program:sshd]" | sudo tee -a /etc/supervisor/supervisord.conf \
    && echo "command=/usr/sbin/sshd -D" | sudo tee -a /etc/supervisor/supervisord.conf  && \
	echo "[program:Xvfb]" | sudo tee -a /etc/supervisor/supervisord.conf \
	&& echo "command=/usr/bin/Xvfb $DISPLAY -screen 0 1920x1080x16" | sudo tee -a /etc/supervisor/supervisord.conf && \
	echo "[program:fluxbox]" | sudo tee -a /etc/supervisor/supervisord.conf \
	&& echo "command=/usr/bin/fluxbox" | sudo tee -a /etc/supervisor/supervisord.conf && \
	echo "[program:x11vnc]" | sudo tee -a /etc/supervisor/supervisord.conf \
	&& echo "command=/usr/bin/x11vnc -display $DISPLAY -bg -loop -forever -xkb -rfbauth $RFBAUTH_PASSWORD_FILE" | sudo tee -a /etc/supervisor/supervisord.conf

# install general tools
RUN sudo apt-get install -y iproute2 vim git inetutils-ping netcat libtool autoconf build-essential firefox-esr zip

# Clone protobuf and install it
WORKDIR /home/nutch/
RUN git clone https://github.com/protocolbuffers/protobuf.git protobuf
WORKDIR /home/nutch/protobuf/
RUN git checkout tags/v2.5.0 
RUN git submodule add https://github.com/google/googletest.git gtest
WORKDIR /home/nutch/protobuf/gtest/
RUN git checkout tags/release-1.5.0
WORKDIR /home/nutch/protobuf/
RUN ./autogen.sh && ./configure && make check && sudo make install && sudo ldconfig

# Copy hadoop 2.7.4
WORKDIR /home/nutch/
ADD hadoop-2.7.4/src/hadoop-dist/target/hadoop-2.7.4 hadoop
ENV HADOOP_HOME=/home/nutch/hadoop/
ADD hadoopconf $HADOOP_HOME/etc/hadoop/
RUN sudo chmod -R 777 $HADOOP_HOME
RUN $HADOOP_HOME/bin/hdfs namenode -format
RUN sudo chmod -R 777 $HADOOP_HOME
ENV PATH="${HADOOP_HOME}/bin:${PATH}"

# Copy nutch 1.15
WORKDIR /home/nutch/
ADD nutch/runtime/deploy nutch
ENV NUTCH_HOME=/home/nutch/nutch/

# Copy geckodriver
WORKDIR /home/nutch/nutch/
ADD geckodriver-v0.24.0-linux64/geckodriver .
RUN sudo chmod -R 777 $NUTCH_HOME

RUN sudo apt-get clean

CMD [ "sudo", "/usr/bin/supervisord" , "-n" ]
